const data = [
  {
    physicalQuantity: "Area",
    units: [
      "Square Kilometre",
      "Square Metre",
      "Square Mile",
      "Square Yard",
      "Square Foot",
      "Square Inch",
      "Hectare",
      "Acre",
    ],
  },
  {
    physicalQuantity: "Data Transfer Rate",
    units: [
      "Bit per second",
      "Kilobit per second",
      "Kilobyte per second",
      "Kibibit per second",
      "Megabit per second",
      "Megabyte per second",
      "Mebibit per second",
      "Gigabit per second",
      "Gigabyte per second",
      "Gibibit per second",
      "Terabit per second",
      "Terabyte per second",
      "Tebibit per second",
    ],
  },
  {
    physicalQuantity: "Digital Storage",
    units: [
      "Bit",
      "Kilobit",
      "Kibibit",
      "Megabit",
      "Mebibit",
      "Gigabit",
      "Gibibit",
      "Terabit",
      "Tebibit",
      "Petabit",
      "Pebibit",
      "Byte",
      "Kilobyte",
      "Kibibyte",
      "Megabyte",
      "Mebibyte",
      "Gigabyte",
      "Gibibyte",
      "Terabyte",
      "Tebibyte",
      "Petabyte",
      "Pebibyte",
    ],
  },
  {
    physicalQuantity: "Energy",
    units: [
      "Joule",
      "Kilojoule",
      "Gram Calorie",
      "Kilocalorie",
      "Watt Hour",
      "Kilowatt Hour",
      "Electronvolt",
      "British Thermal Unit",
      "US therm",
      "Foot-ound",
    ],
  },
  {
    physicalQuantity: "Frequency",
    units: ["Hertz", "Kilohertz", "Megahertz", "Gigahertz"],
  },
  {
    physicalQuantity: "Length",
    units: [
      "Kilometre",
      "Metre",
      "Centimetre",
      "Milimetre",
      "Micrometre",
      "Nanometre",
      "Mile",
      "Yard",
      "Foot",
      "Inch",
      "Nautical Mile",
    ],
  },
  {
    physicalQuantity: "Mass",
    units: [
      "Milligram",
      "Gram",
      "Kilogram",
      "Metric ton",
      "Ounce",
      "Pound",
      "Stone",
      "US ton",
      "Imperial ton",
    ],
  },
  {
    physicalQuantity: "Plane Angle",
    units: ["Arcsecond", "Degree", "Gradian", "Milliradian", "Minute of arc"],
  },
  {
    physicalQuantity: "Pressure",
    units: [
      "Bar",
      "Pascal",
      "Pound per square inch",
      "Standard Atmosphere (atm)",
      "Torr",
    ],
  },
  {
    physicalQuantity: "Speed",
    units: [
      "Metre per second",
      "Foot per second",
      "Kilometre per hour",
      "Knot",
    ],
  },
  {
    physicalQuantity: "Temperature",
    units: ["Kelvin", "Celcius", "Fahrenheit", "Reamur"],
  },
  {
    physicalQuantity: "Time",
    units: [
      "Nanosecond",
      "Microsecond",
      "Milisecond",
      "Second",
      "Minute",
      "Hour",
      "Day",
      "Week",
      "Month",
      "Year",
      "Decade",
      "Century",
    ],
  },
  {
    physicalQuantity: "Volume",
    units: [
      "Cubic Metre",
      "Liter",
      "Milliliter",
      "Cubic Foot",
      "Cubic Inch",
      "Imperial Gallon",
      "Imperial Quart",
      "Imperial pint",
      "Imperial Cup",
      "Imperial Fluid Ounce",
      "Imperial tablespoon",
      "Imperial Teaspoon",
      "US Liquid Gallon",
      "US Liquid Quart",
      "US Liquid pint",
      "US legal Cup",
      "US Fluid Ounce",
      "US tablespoon",
      "US Teaspoon",
    ],
  },
];

const conversion = [
  {
    physicalQuantityConversion: "Area",
    formulas: [
      { pair: "Celcius to Fahrenheit", formula: (c) => (9 / 5) * c + 32 },
      { pair: "Celcius to Reamur", formula: (c) => (4 / 5) * c },
      { pair: "Celcius to Kelvin", formula: (c) => c + 273.15 },
      { pair: "Fahrenheit to Celcius", formula: (f) => (f - 32) * (5 / 9) },
      { pair: "Fahrenheit to Reamur", formula: (f) => (4 / 9) * (f - 32) },
      {
        pair: "Fahrenheit to Kelvin",
        formula: (f) => (5 / 9) * (f - 32) + 273.15,
      },
      { pair: "Reamur to Celcius", formula: (r) => (5 / 4) * r },
      { pair: "Reamur to Fahrenheit", formula: (r) => (9 / 4) * r + 32 },
      { pair: "Reamur to Kelvin", formula: (r) => (5 / 4) * r + 273.15 },
      { pair: "Kelvin to Celcius", formula: (k) => k - 273.15 },
      {
        pair: "Kelvin to Fahrenheit",
        formula: (k) => ((k - 273.15) * 9) / 5 + 32,
      },
      { pair: "Kelvin to Reamur", formula: (k) => ((k - 273.15) * 4) / 5 },
    ],
  },
  {
    physicalQuantityConversion: "Data Transfer Rate",
    formulas: [
      { pair: "Celcius to Fahrenheit", formula: (c) => (9 / 5) * c + 32 },
      { pair: "Celcius to Reamur", formula: (c) => (4 / 5) * c },
      { pair: "Celcius to Kelvin", formula: (c) => c + 273.15 },
      { pair: "Fahrenheit to Celcius", formula: (f) => (f - 32) * (5 / 9) },
      { pair: "Fahrenheit to Reamur", formula: (f) => (4 / 9) * (f - 32) },
      {
        pair: "Fahrenheit to Kelvin",
        formula: (f) => (5 / 9) * (f - 32) + 273.15,
      },
      { pair: "Reamur to Celcius", formula: (r) => (5 / 4) * r },
      { pair: "Reamur to Fahrenheit", formula: (r) => (9 / 4) * r + 32 },
      { pair: "Reamur to Kelvin", formula: (r) => (5 / 4) * r + 273.15 },
      { pair: "Kelvin to Celcius", formula: (k) => k - 273.15 },
      {
        pair: "Kelvin to Fahrenheit",
        formula: (k) => ((k - 273.15) * 9) / 5 + 32,
      },
      { pair: "Kelvin to Reamur", formula: (k) => ((k - 273.15) * 4) / 5 },
    ],
  },
  {
    physicalQuantityConversion: "Temperature",
    formulas: [
      { pair: "Celcius to Fahrenheit", formula: (c) => (9 / 5) * c + 32 },
      { pair: "Celcius to Reamur", formula: (c) => (4 / 5) * c },
      { pair: "Celcius to Kelvin", formula: (c) => c + 273.15 },
      { pair: "Fahrenheit to Celcius", formula: (f) => (f - 32) * (5 / 9) },
      { pair: "Fahrenheit to Reamur", formula: (f) => (4 / 9) * (f - 32) },
      {
        pair: "Fahrenheit to Kelvin",
        formula: (f) => (5 / 9) * (f - 32) + 273.15,
      },
      { pair: "Reamur to Celcius", formula: (r) => (5 / 4) * r },
      { pair: "Reamur to Fahrenheit", formula: (r) => (9 / 4) * r + 32 },
      { pair: "Reamur to Kelvin", formula: (r) => (5 / 4) * r + 273.15 },
      { pair: "Kelvin to Celcius", formula: (k) => k - 273.15 },
      {
        pair: "Kelvin to Fahrenheit",
        formula: (k) => ((k - 273.15) * 9) / 5 + 32,
      },
      { pair: "Kelvin to Reamur", formula: (k) => ((k - 273.15) * 4) / 5 },
    ],
  },
];

export default data;
